# Generated by Django 4.2.1 on 2023-05-20 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_flashnews'),
    ]

    operations = [
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slideImage', models.ImageField(upload_to='slider/')),
                ('slideeHeader', models.CharField(max_length=50)),
                ('slideTitle', models.CharField(max_length=100)),
                ('slideSubtitle', models.CharField(max_length=200)),
                ('slideBottomtitle', models.CharField(max_length=100)),
            ],
        ),
    ]
