# Generated by Django 4.2.1 on 2023-05-20 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_slider'),
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CardTitle', models.CharField(max_length=150)),
                ('CardBottomTitle', models.CharField(max_length=100)),
                ('CardImage', models.ImageField(upload_to='card/')),
            ],
        ),
    ]
