# Generated by Django 4.2.1 on 2023-05-21 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_card'),
    ]

    operations = [
        migrations.CreateModel(
            name='BreakingNews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('newsImage', models.ImageField(upload_to='breakingnews/')),
                ('newsHeader', models.CharField(max_length=100)),
                ('newsinfo', models.CharField(max_length=50)),
                ('newstitle', models.CharField(max_length=100)),
            ],
        ),
    ]
