# Generated by Django 4.2.1 on 2023-05-22 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_breakingnews'),
    ]

    operations = [
        migrations.CreateModel(
            name='video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('VideoImage', models.ImageField(upload_to='video/')),
                ('videoTitle', models.CharField(max_length=100)),
            ],
        ),
    ]
